{
 "title": "Online Shop API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Average request duration over the last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (increase(http_request_duration_seconds_sum[1m])) / sum by(__name__) (increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Average request duration"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}